export const SET_WEEKLY_RECEIPT = "SET_WEEKLY_RECEIPT";
export const ADD_WEEKLY_RECEIPT = "ADD_WEEKLY_RECEIPT";
export const ADD_ORDER_TO_WEEKLY_RECEIPT = "ADD_ORDER_TO_WEEKLY_RECEIPT";
export const GET_WEEKLY_RECEIPTS_FOR_DATE = "GET_WEEKLY_RECEIPTS_FOR_DATE";
export const GET_WEEKLY_RECEIPT_AND_ORDERS = "GET_WEEKLY_RECEIPT_AND_ORDERS";
